### PR TITLE
Clean up unnecessary babel transforms and update node-sass

### PR DESCRIPTION
**Pull request by i-like-robots**

### CODE REVIEW

**Comment by i-like-robots** [comment]
CC @bjfletcher

**Comment by bjfletcher** [comment]
Thanks, Matt!

Is `babel-plugin-add-module-exports` necessary having `babel-plugin-transform-es2015-modules-commonjs`?

**Comment by bjfletcher** [comment]
BTW... `babel-plugin-transform-es2015-modules-commonjs` and `babel-preset-node6` are identical :) (The latter having just the first in its list of plugins.)

**Comment by i-like-robots** [comment]
I don't think there's any harm going with a preset - I'm not sure of the reasons historically why we would choose _not_ to use them.

**Comment by i-like-robots** [comment]
`babel-plugin-add-module-exports` is necessary (for now) because Babel did their own thing with ES6 modules. That means any module that tries to `require` an ES6 module has to add `.default`

**Pull request merged**
