### PR TITLE
Add myFT Tray

### PR DESCRIPTION
**Pull request by adgad**
/cc @charypar @imranolas @wheresrhys 

myft-tray-hp

### CODE REVIEW

**Comment by charypar** [comment]
Also need to discuss with Bede. Don't merge.

**Comment by commuterjoy** [comment]
+1 good collaboration between teams here.

**Comment by adgad** [comment]
Yup, I think James is on top of speaking to Bede, will wait till then :)

**Comment by commuterjoy** [comment]
@charypar 

> +{{#if @root.flags.myFTTray}}

it's behind a flag

**Comment by charypar** [comment]
As per email from James Webb - This won’t be implemented on the homepage for now. It was agreed that recency and frequency team would work with us to figure out an alternative design approach for the red blob once we complete work on the navigation.

**Pull request closed without merging**
