### PR TITLE
Use next-sass-setup rather than its indidvidual dependencies (resolves #12)

### LINKED ISSUE #12: Switch back to next-sass-setup
This requires a bit of work on `next-sass-setup` and updates to how we use `o-colors`.

### PR DESCRIPTION
**Pull request by charypar**
- [x] include `next-sass-setup`
- [x] use `o-colors` properly

### CODE REVIEW

**Comment by charypar** [comment]
I also realised we do need o-grid generated anyway for header and footer, so there is no need to change next-sass-setup.

**Comment by charypar** [comment]
@keirog, @kaelig would you mind having a look at this before we merge to make sure we're not doing something stupid?

**Comment by keirog** [comment]
Looks fine to me. General comment on color usage though: I imagine the Origami folks would be keener for you to use one of their [o-colors mixins/functions](https://github.com/Financial-Times/o-colors#use-case-mixin), rather than a `map-get` on the the palette map… @kaelig?

**Comment by charypar** [comment]
@keirog I looked for one to define new custom colors, but couldn't find one, hence extending the palette with `map-merge`. It's meant to be temporary until we settle on a set of colors and are happy, then merging it int `o-colors` and defining use-cases properly.

**Comment by charypar** [comment]
Hang on, misread your comment, are we using `map-get` anywhere?

**Comment by charypar** [comment]
@keirog using `oColorsGetPaletteColor` now.

**Comment by keirog** [comment]
:+1: nice, go for it

**Pull request merged**
