### PR TITLE
Hide alt text on images

### PR DESCRIPTION
**Pull request by charypar**
All of them are illustrational.

@i-like-robots

### CODE REVIEW

**Comment by ironsidevsquincy** [comment]
:+1:

**Comment by i-like-robots** [comment]
On the image elements themselves (if you can) it would be good to add `role="presentational"` just so any screen reader user isn't subjected to their software trying to interpret the filename into something.

**Comment by charypar** [comment]
@i-like-robots would have to do it in n-image. But what it does is leave `alt` empty, which I think is equivalent?

**Comment by i-like-robots** [comment]
In theory but not in reality - yet =(

**Comment by charypar** [comment]
Issue on n-image then?

**Pull request merged**
