### PR TITLE
Try to go without `bower` as a dev dependency

### PR DESCRIPTION
**Pull request by matthew-andrews**

### CODE REVIEW

**Comment by matthew-andrews** [comment]
I don't think this is failing because of bower.

**Comment by charypar** [comment]
@matthew-andrews What's this for? Is it still relevant?

**Comment by matthew-andrews** [comment]
Yes, apps shouldnt really have `bower` as a dev dep.  Let me try rebasing.

**Comment by ironsidevsquincy** [comment]
This was just while obt was playing up

**Comment by charypar** [comment]
in that case :+1:

**Comment by matthew-andrews** [comment]
success!!!

**Comment by matthew-andrews** [comment]
success!!!

**Pull request merged**
