### PR TITLE
Added message prompts client

### PR DESCRIPTION
**Pull request by ifyio**
cc/ @tom-parker @adambraimbridge

### CODE REVIEW

**Comment by adambraimbridge** [comment]
:+1:

**Comment by charypar** [comment]
@ifyio Can you give a bit more context on what this does? Are those the pop-ups on the bottom we've seen in the Monday meeting or am I getting confused?

Also, if it's a user facing thing, we (home page stream) would appreciate a chance to check with Gadi that he's ok with us shipping it (which I'm sure he is, just want to make sure). Since I am personally unclear on what this is, it makes me uneasy when it just goes in.

**Comment by ifyio** [comment]
@charypar yes sure. It's the javascript / css that sets up and displays the discount message prompt on the site. This message prompt is shown at the bottom left of the page and it is only shown when an anonymous user has been presented with a barrier / product selector and then navigates to another page. It is indeed the popup that we saw in the Monday meeting. Apologies for not giving you guys a chance to look it over. Will make sure to not do that next time around.

**Comment by charypar** [comment]
@ifyio Great thanks!

**Pull request merged**
