### PR TITLE
[WIP][DON'T MERGE] Migrating any use of next-ads-component to n-third-party-code

### PR DESCRIPTION
**Pull request by adambraimbridge**
Note: This makes the "frontPageAds" flag obsolete

### CODE REVIEW

**Comment by charypar** [comment]
@adambraimbridge that flag is no longer necessary anyway, fine to remove completely.

**Comment by adambraimbridge** [comment]
Thanks @charypar — for the record I'm ignoring the `responsiveAds` and `richMediaAds` flags, too.

**Comment by adambraimbridge** [comment]
@charypar : Once https://github.com/Financial-Times/next-js-setup/pull/84 is merged, it'll handle all ads (via `n-third-party-code`). Hence this PR which removes `next-ads-component` from `next-front-page`. Okay with you if I merge when ready?

**Comment by charypar** [comment]
@adambraimbridge yep :+1:

**Pull request merged**
