### PR TITLE
Update Brexit poll countdown text

### PR DESCRIPTION
**Pull request by sumeetadur**
screen shot 2016-06-03 at 14 58 54

### CODE REVIEW

**Comment by sumeetadur** [comment]
@ironsidevsquincy could you have a look?

**Comment by ironsidevsquincy** [comment]
Do we know how many days before we're going to show the countdown? i.e. could we add, say

```
if (daystogo > 10) {
    return 'Latest polls';
} else if (daystogo > 1) {
    return `${daystogo} days until the referendum`;
}
```

To the existing function, rather than doing a code change

**Comment by sumeetadur** [comment]
Unfortunately we don't know, it's an editorial decision that hasn't been made yet

**Comment by ironsidevsquincy** [comment]
Shame, 👍

**Pull request merged**
