### PR TITLE
o-hoverable override

### PR DESCRIPTION
**Pull request by gvonkoss**
@onishiweb ?

### CODE REVIEW

**Comment by onishiweb** [comment]
@gvonkoss ?

**Comment by lc512k** [comment]
@onishiweb iirc it's the same issue we were looking at yesterday where `.o-hoverable-on a:hover` is overriding the hover style in o-teaser. Could we increase specificity there rather than `!important`?

**Comment by onishiweb** [comment]
If needed I can add the `.o-hoverable-on` class to the specificity of the selector in `o-teaser`?

**Comment by gvonkoss** [comment]
sounds like that would be better than `!important` 🙈

**Comment by onishiweb** [comment]
Released: https://github.com/Financial-Times/o-teaser/releases/tag/v1.11.0 see if that works :)

**Pull request closed without merging**
