### PR TITLE
If no content, dont render section

### PR DESCRIPTION
**Pull request by adgad**
/cc @ironsidevsquincy @andygout @matthew-andrews

### CODE REVIEW

**Comment by matthew-andrews** [comment]
this is fine for most sections but i _think_ the top stories section should always try render and trigger 5xx (and hope that Fastly will serve stale instead)…  is that compatible with this change?

**Comment by adgad** [comment]
[This](https://github.com/Financial-Times/next-front-page/blob/master/server/routes/front-page.js#L8) should have been - but the property has been renamed since :( 

I will fix and write a test.

**Comment by andygout** [comment]
More for my education, but what is difference between:-

```js
if(!(this.state.content && this.state.content.main && this.state.content.main.length)) {
	return null;
 }
```

and

```js
if(!this.state.content.main.length) {
	return null;
 }
```
?  On the surface it seems this single statement queries the desired status?

**Comment by adgad** [comment]
If `this.state.content` is null, then trying to access `this.state.content.main` will throw an error.

**Comment by andygout** [comment]
And it'll check each one in sequence so will only hit a null rather than an error - got it, thanks!

**Comment by adgad** [comment]
(The property hadn't been renamed - i misread. But added the other first top story to that check as well)

**Pull request merged**
