### PR TITLE
Add: Temporary fix for Chrome v.48 element 'wiggle' bug

### PR DESCRIPTION
**Pull request by andygout**
cc @ironsidevsquincy @adgad

### CODE REVIEW

**Comment by ironsidevsquincy** [comment]
:+1:

**Comment by keirog** [comment]
:cry:

**Comment by matthew-andrews** [comment]
this is arguably a better way to do underlining of text anyway :grin:

**Comment by adgad** [comment]
Interestingly text-decoration-style looks like it's been removed from Chrome Canary
(maybe not so interesting as it's [not actually supported](https://developer.mozilla.org/en/docs/Web/CSS/text-decoration-style)

**Comment by andygout** [comment]
Kept that in so that Firefox users at least have a more consistent experience until Chrome release with fix arrives (I've got a reminder in the diary for when Chrome 49 is released to check if we can revert styling).

**Comment by adgad** [comment]
Ah, I saw it in Chrome 48 with the Experimental Web Features flag on - so probably still is in Canary with that flag on)

**Pull request merged**
